# Auto-generated by /bdd-writer from repo-model execution flow
# Flow: admin-panel
@admin
Feature: Admin panel for platform management
  As a platform administrator
  I want to manage campaigns, flags, and content via the admin panel
  So that I can operate ai-grija.ro without deploying code changes

  Background:
    Given the admin panel is served at admin.ai-grija.ro
    And CF Access authentication is enforced

  @admin @auth
  Scenario: Unauthenticated requests are blocked by CF Access
    Given a user without CF Access credentials
    When the user requests admin.ai-grija.ro
    Then CF Access redirects to the login page
    And no admin content is served

  @admin @dashboard
  Scenario: Authenticated admin views the dashboard
    Given an admin with valid CF Access JWT
    When the admin navigates to admin.ai-grija.ro/
    Then the dashboard shows system statistics
    And the response includes CSP nonce for inline scripts

  @admin @campaigns
  Scenario: Admin views the campaigns list
    Given an authenticated admin
    When the admin navigates to the campaigns page
    Then active campaigns are displayed with severity badges
    And campaign data is properly HTML-escaped
