# Auto-generated by /bdd-writer from repo-model execution flow
# Flow: blog-content
@blog
Feature: Blog and educational content
  As a Romanian internet user
  I want to read educational articles about online safety
  So that I can learn to identify phishing attempts

  Background:
    Given the ai-grija.ro API is running
    And the Sanity CMS is configured

  @blog @list
  Scenario: User browses the blog post list
    Given blog posts exist in Sanity CMS
    When the user GETs /blog
    Then an SSR page is returned with the list of posts
    And each post shows title, summary, and reading time

  @blog @detail
  Scenario: User reads a specific blog post
    Given a blog post with slug "cum-recunosti-phishing" exists
    When the user GETs /blog/cum-recunosti-phishing
    Then the full SSR blog page is returned with content
    And Open Graph meta tags are present for social sharing

  @blog @test-env
  Scenario: Mock data is returned in test and dev environments
    Given the ENVIRONMENT is set to "test"
    When the user GETs /blog
    Then mock blog data is returned from sanity-mock-data.ts
    And no external Sanity API call is made

  @blog @i18n
  Scenario: Content categories display translated names
    Given the user's language is Romanian
    When the user browses to a content category page
    Then the category title uses the translated name from i18n
    And the category slug is not shown as raw text
