# Auto-generated by /bdd-writer from repo-model execution flow
# Flow: community-report
@community-reports
Feature: Community scam reporting and voting
  As a Romanian citizen who encountered a scam
  I want to report and vote on phishing attempts
  So that the community can track active scam campaigns

  @community-reports @list
  Scenario: User views the community reports feed
    Given community reports exist in the KV store
    When the user GETs /api/reports
    Then the response contains up to 20 reports sorted by votes
    And each report includes id, text snippet, votes, verdict, and timestamp

  @community-reports @legacy
  Scenario: Legacy report-index entries are visible after migration
    Given reports were created before the per-key index migration
    And those reports exist under the legacy "report-index" key
    When the user GETs /api/reports
    Then legacy reports appear alongside new per-key indexed reports

  @community-reports @vote
  Scenario: User upvotes a community report
    Given a community report with id "r123" exists
    When the user POSTs to /api/reports/r123/vote with vote "up"
    Then the votes_up count increments by 1
    And the cached reports list is invalidated

  @community-reports @rate-limit
  Scenario: Vote rate limiting prevents ballot stuffing
    Given a user has voted 10 times in the current window
    When the user POSTs another vote
    Then the response status is 429
    And the message says "Ai votat prea mult"
