# Auto-generated by /bdd-writer from repo-model execution flow
# Flow: image-check
@image-check
Feature: Screenshot-based phishing detection
  As a Romanian internet user
  I want to upload a screenshot of a suspicious message
  So that AI can analyze images I cannot copy as text

  Background:
    Given the ai-grija.ro API is running
    And the Workers AI vision model (Llava) is available
    And R2 storage is configured for temporary image storage

  @image-check @upload
  Scenario: User uploads a valid screenshot for analysis
    Given the user has a PNG screenshot under 5MB
    When the user POSTs the image to /api/check/image
    Then the image is validated for type and size
    And the image is stored temporarily in R2
    And the vision model analyzes the image content
    And the response contains a verdict

  @image-check @validation
  Scenario: Oversized images are rejected
    Given the user has an image larger than 5MB
    When the user POSTs the image to /api/check/image
    Then the response status is 400
    And the response contains an error about file size

  @image-check @validation
  Scenario: Invalid file types are rejected
    Given the user uploads a .exe file disguised as an image
    When the user POSTs the file to /api/check/image
    Then the response status is 400
    And the response contains an error about file type
