# Auto-generated by /bdd-writer from repo-model execution flow
# Flow: phishing-check
@phishing-check
Feature: Phishing message verification
  As a Romanian internet user
  I want to check if a suspicious message is phishing
  So that I can protect myself from online fraud

  Background:
    Given the ai-grija.ro API is running
    And the Workers AI classifier is available

  @phishing-check @api
  Scenario: User submits a suspicious text message for analysis
    Given a user has received a suspicious SMS or WhatsApp message
    When the user POSTs the message text to /api/check
    Then the response contains a verdict of "phishing", "suspicious", or "likely_safe"
    And the response contains a confidence score between 0 and 1
    And the response contains a list of red flags

  @phishing-check @pii
  Scenario: PII is redacted before AI classification
    Given a message containing a Romanian CNP "1234567890123"
    When the user POSTs the message to /api/check
    Then the CNP is replaced with "[REDACTAT]" before reaching the classifier
    And the original PII is never stored or logged

  @phishing-check @rate-limit
  Scenario: Rate limiting prevents abuse of the check endpoint
    Given a user has exceeded the rate limit for /api/check
    When the user POSTs another message to /api/check
    Then the response status is 429
    And the response contains "RATE_LIMITED" error code
    And X-RateLimit-Remaining header is 0

  @phishing-check @campaign
  Scenario: Known campaign patterns are detected and matched
    Given the message matches a known phishing campaign pattern
    When the user POSTs the message to /api/check
    Then the response includes campaign match details
    And the response includes bank-specific instructions if applicable

  @phishing-check @domain
  Scenario: Suspicious URLs in the message are analyzed
    Given the message contains a URL that mimics a legitimate Romanian bank domain
    When the user POSTs the message to /api/check
    Then the domain analysis section shows "Domeniu Suspect"
    And the risk score is above 0.5
