# Auto-generated by /bdd-writer from repo-model execution flow
# Flow: scheduled-crons
@crons
Feature: Scheduled background jobs
  As a platform operator
  I want automated background tasks to run on schedule
  So that content stays fresh and data is managed without manual intervention

  @crons @daily
  Scenario: Campaign scraper runs daily at midnight
    Given the cron trigger fires at "0 0 * * *"
    When the scheduled handler dispatches the campaign scraper
    Then known phishing campaigns are updated from external sources
    And the campaign data in KV is refreshed

  @crons @cleanup
  Scenario: R2 share card cleanup runs daily
    Given the cron trigger fires at "0 1 * * *"
    When the scheduled handler dispatches the R2 cleanup
    Then share cards older than 30 days are deleted from R2
    And storage costs are controlled

  @crons @content
  Scenario: AI educational content is generated on weekdays
    Given the cron trigger fires at "0 2 * * 1-5"
    When the scheduled handler dispatches the content generator
    Then a new educational article draft is created via Workers AI
    And the draft is queued for review

  @crons @digest
  Scenario: Weekly digest is sent on Mondays
    Given the cron trigger fires at "0 6 * * 1"
    When the scheduled handler dispatches the weekly digest
    Then subscribers receive a summary of the week's phishing alerts

  @crons @gdpr
  Scenario: GDPR auto-purge runs monthly
    Given the cron trigger fires at "0 0 1 * *"
    When the scheduled handler dispatches the GDPR purge
    Then inactive subscriber data older than 12 months is deleted
    And consent records are preserved for 5 years per legal requirement
