# Auto-generated by /bdd-writer from repo-model execution flow
# Flow: spa-serving
@spa
Feature: Single-page application serving
  As a visitor to ai-grija.ro
  I want the website to load quickly with all assets
  So that I can use the phishing checker and browse content

  @spa @homepage
  Scenario: Homepage loads with SPA shell and assets
    Given a browser requests https://ai-grija.ro/
    When the Worker receives the request
    Then the ASSETS binding serves index.html
    And the response is cloned for mutable headers
    And security headers (HSTS, X-Content-Type-Options) are applied
    And the response status is 200

  @spa @routing
  Scenario: Hash-based SPA routes resolve correctly
    Given a browser navigates to https://ai-grija.ro/#/blog
    When the Worker receives the request for /
    Then index.html is served (SPA fallback)
    And the React router handles the hash route client-side

  @spa @assets
  Scenario: Static JS and CSS assets are served with correct content types
    Given the SPA references /assets/index-*.js and /assets/index-*.css
    When the browser requests these asset URLs
    Then the response content-type is "text/javascript" for JS files
    And the response content-type is "text/css" for CSS files
    And the response status is 200

  @spa @404
  Scenario: Unknown file extensions return 404 not SPA fallback
    Given a browser requests /nonexistent.json
    When the Worker receives the request
    Then the response status is 404
    And the response is JSON with error code "NOT_FOUND"
    And index.html is NOT served
