# Auto-generated by /bdd-writer from repo-model execution flow
# Flow: telegram-webhook
@telegram-bot
Feature: Telegram bot for phishing verification
  As a Romanian Telegram user
  I want to verify suspicious messages via the ai-grija bot
  So that I can check scams without visiting the website

  Background:
    Given the Telegram webhook is configured at /webhook/telegram
    And the bot token is bound via env.TELEGRAM_BOT_TOKEN

  @telegram-bot @commands
  Scenario: User starts the bot with /start command
    Given a Telegram user sends "/start" to the bot
    When the webhook receives the update
    Then the bot responds with a welcome message in Romanian
    And the user's chat_id is stored for notifications

  @telegram-bot @check
  Scenario: User sends a suspicious message for verification
    Given a Telegram user sends "/verifica Am primit un SMS de la Posta Romana"
    When the webhook receives the update
    Then the classifier analyzes the message
    And the bot responds with the verdict and red flags

  @telegram-bot @gdpr
  Scenario: User deletes their data with /sterge command
    Given a Telegram user previously subscribed with /start
    When the user sends "/sterge" to the bot
    Then the user's chat_id and subscription data are deleted
    And the bot confirms deletion
