# Auto-generated by /bdd-writer from repo-model execution flow
# Flow: whatsapp-webhook
@whatsapp-bot
Feature: WhatsApp bot for phishing verification
  As a Romanian WhatsApp user
  I want to forward suspicious messages to the ai-grija bot
  So that I can quickly check if a message is a scam

  Background:
    Given the WhatsApp webhook is configured at /webhook/whatsapp
    And the WhatsApp Cloud API token is bound

  @whatsapp-bot @check
  Scenario: User sends a suspicious message for verification
    Given a WhatsApp user forwards a suspicious message to the bot
    When the webhook receives the message
    Then the rate limiter checks per-sender quota
    And the classifier analyzes the message
    And the bot responds with the verdict via WhatsApp Cloud API

  @whatsapp-bot @rate-limit
  Scenario: Per-sender rate limiting prevents abuse
    Given a WhatsApp user has exceeded their message quota
    When the user sends another message
    Then the bot responds with a rate limit message in Romanian

  @whatsapp-bot @gdpr
  Scenario: User opts out with STERGE keyword
    Given a WhatsApp user sends "STERGE"
    When the webhook receives the message
    Then the user's phone number and data are deleted
    And the bot confirms deletion
